baseURL: "http://european-erlang.community/"
languageCode: "en-us"
title: "European Erlang Community"
theme: hugo-fresh

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  openGraph: true
  description: "European Erlang is a free and open organization"
  # navbarlogo:
  #  image: "logos/european-erlang-community-black.svg"
  #  link: "/"
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: "European Erlang Community"
    subtitle: "Share your knowledge with other"
    buttontext: "Get started"
    buttonlink: "#"
    image: illustrations/worker.svg
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  navbar:
  - title: About
    url: /
  - title: Statutes
    url: /
  - title: Services
    sublinks:
    - title: Directory
      url: /
    - title: Consulting
      url: /
    - title: Mentoring
      url: /
    - title: Meetup
      url: /
  - title: Contact us
    url: /
    button: true
    
  section1:
    title: "An Open Erlang Community"
    subtitle: "for everyone in Europe and beyond!"
    tiles:
    - title: "Directory"
      # icon: "directory"
      text: "A place to meet people, find new ideas and make business."
      url: /
      buttonText: "Access it"
    - title: "Consulting"
      # icon: consulting
      text: "A place to help you and your projects."
      url: /
      buttonText: "Ask us"
    - title: "Mentoring"
      # icon: mentoring
      text: "A place to be safe and share your ideas."
      url: /
      buttonText: "Engage"
      
  section2:
    title: "You're here because you want to know more..."
    subtitle: "And will give you what you need!"
    features:
    
    - title: Directory
      text: "An active community, lead by the will of sharing and helping each others."
      
    - title: Consulting
      text: "You are almost certain that Erlang is a good answer for your project(s). We are here to make it an absolute certainty."

    - title: Mentoring
      text: "Learning a new programming language, or a new framework, is not easy. It's even more true when you are starting a new project. We are here to give you advices and help you to find the your way."
      
    - title: Events
      text: "Sharing is in our DNA, the best way to share is to meet in real life. We are planning meetups and conferences in Europe."
      
  footer:
    logo: eec2.svg
    socialmediatitle: Follow Us
    socialmedia:
    - link: https://github.com/european-erlang
      icon: github
    - link: https://twitter.com/EuropeanErlang
      icon: twitter
